### ISSUE TITLE
Re-constituting GMT Steering Committee (nominations due July 24)

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/oversight#9]
Following up on the new governance structure from #7 , it's time to re-constitute a steering committee. Please post here if you'd like to nominate someone else or yourself for steering committee membership by July 24. If you would like to nominate someone but don't want to post on GitHub, please email me at maxjones@hawaii.edu As a reminder, these are the responsibilities for the steering committee:

> - Attend a one-hour steering committee meeting every six months.
> - Respond in a timely manner to steering-committee-related correspondence.
> - Act as an ambassador for the project in professional contexts.
> 
> The chair of the Steering Committee is expected to arrange the regular meetings and ensure that a report is shared with the community.

As mentioned in #7, active and previous core developers of GMT, wrappers, and related tools will decide on the Steering Committee based on these nominations, provided the nominee is interested. Please let me know if I'm missing anyone who should be involved in this decision: Joaqium, Dongdong , Leo, Walter, Dave Caress, David Sandwell, Wei Ji, Remko, Yvonne, Michael, Will, Federico

cc @GenericMappingTools/core @GenericMappingTools/pygmt-team

**Comment by maxrjones** [comment]
To kick things off, I would like to nominate Walter Smith and David Sandwell.

**Comment by joa-quim** [comment]
> Please let me know if I'm missing anyone who should be involved in this decision: 

Federico Esteban must be involved too.

**Comment by joa-quim** [comment]
During the discussion phase I had proposed. Remember that David Sandwell mentioned Eric instead of himself

-    Joaquim Luis
-    Remko Scharroo
-    Dongdong Tian
-    Federico Esteban
-    Eric Xu
-    Dave Caress

**Comment by maxrjones** [comment]
> > Please let me know if I'm missing anyone who should be involved in this decision:
> 
> Hi,
> 
> Federico Esteban must be involved too.

Thanks, and sorry for my initial mistake Federico! I unfortunately wrote the issue while extremely jet-lagged

**Comment by yvonnefroehlich** [comment]
Thanks, @maxrjones for mentioning! I will read through this and related PRs / issues in the next day / on the weekend to get an overview.

**Comment by michaelgrund** [comment]
I'm fine with the proposed people, thanks for your efforts.

**Comment by yvonnefroehlich** [comment]
I'm fine with the proposed people.

**Comment by seisman** [comment]
@maxrjones Has the new GMT steering committee been finalized? Is it time to update the committee members in this repository and on the GMT website?

**Comment by maxrjones** [comment]
> @maxrjones Has the new GMT steering committee been finalized? Is it time to update the committee members in this repository and on the GMT website?

Yes, everyone has responded. I opened https://github.com/GenericMappingTools/oversight/pull/10 to add a list of committee members. Please feel welcome to take over with selecting a chair, organizing meetings, announcing on the website/forum, and anything else necessary. Thanks for your service on the committee!
